# Title: fuck-you-kiki (dnsmasq)
# Homepage: https://github.com/zalofucker/fuck-you-kiki
# ..............
address=/stc-zlogin.zdn.vn/0.0.0.0
address=/id.zalo.me/0.0.0.0
address=/oauth.zaloapp.com/0.0.0.0
address=/zaloapp.com/0.0.0.0
address=/ztevents.zaloapp.com/0.0.0.0
address=/zalo-captcha.zdn.vn/0.0.0.0
address=/logo-zp.zdn.vn/0.0.0.0
address=/developers.zalo.me/0.0.0.0
address=/smarthome.kiki.zalo.ai/0.0.0.0
address=/api.kiki.zalo.ai/0.0.0.0
address=/kiki.zalo.ai/0.0.0.0
address=/zinst-stc.zadn.vn/0.0.0.0
address=/a-fg42.dlfl.vn/0.0.0.0
address=/a-fg40.dlfl.vn/0.0.0.0
address=/a-fg62.dlfl.vn/0.0.0.0
address=/res-zalo.zadn.vn/0.0.0.0
address=/a-fg63.dlfl.vn/0.0.0.0
address=/a-fg41.dlfl.vn/0.0.0.0
address=/log.api.zaloapp.com/0.0.0.0
address=/ads-platform.zalo.me/0.0.0.0
address=/zcaptcha.zdn.vn/0.0.0.0
address=/zalo-captcha.zdn.vn/0.0.0.0
address=/zcaptcha.api.zaloapp.com/0.0.0.0
